import type { HeadingLine } from "@/components/ui/Layout";
import type { Locale } from "./i18n/config.ts";

/**
 * Démonstration interactive de Revenue OS — « Élan Habitat ».
 *
 * ENTREPRISE FICTIVE. Élan Habitat n'existe pas ; ses chiffres, son équipe,
 * ses clients (Thomas Martin, Claire Bernard) et ses résultats sont des
 * données de démonstration. Rien ici ne décrit un client d'AMYN. Chaque
 * écran de la démonstration le rappelle.
 *
 * Les étapes suivent un seul fil : une demande entre, est traitée jusqu'au
 * devis, puis une ancienne demande est réactivée, puis la direction voit
 * l'ensemble, puis on recule pour voir le système entier.
 */

export const DEMO_STAGES = [
  "enquiry",
  "response",
  "qualification",
  "crm",
  "routing",
  "brief",
  "appointment",
  "aftercall",
  "proposal",
  "reactivation",
  "dashboard",
  "finale",
] as const;
export type DemoStageId = (typeof DEMO_STAGES)[number];

/** Nombre d'étapes animées de chaque écran (0 = état initial). */
export const DEMO_STEPS: Record<DemoStageId, number> = {
  enquiry: 4,
  response: 8,
  qualification: 8,
  crm: 10,
  routing: 7,
  brief: 7,
  appointment: 9,
  aftercall: 8,
  proposal: 7,
  reactivation: 12,
  dashboard: 5,
  finale: 6,
};

const nb = " ";
const nn = " ";

const fr = {
  meta: {
    title: "Revenue OS en action — démonstration interactive",
    description:
      "Suivez une demande dans Revenue OS, de la première seconde au devis : réponse, qualification, CRM, attribution, brief, rendez-vous, relances, réactivation et vue direction. Entreprise fictive, données illustratives.",
  },
  fictional: "Démonstration fictive — données illustratives",
  fictionalShort: "Fictif",
  hero: {
    label: "Démonstration interactive",
    title: [{ text: "Revenue OS," }, { accent: "en action." }] as HeadingLine[],
    lead: "Une entreprise de rénovation reçoit une demande un matin à 09:42. Voici ce que fait Revenue OS — de la première seconde jusqu'au devis, puis au-delà.",
    start: "Lancer la démonstration",
    duration: "Environ deux minutes · pause et navigation à tout moment",
  },
  company: {
    name: "Élan Habitat",
    kind: "Rénovation résidentielle haut de gamme",
    location: "Lille & Hauts-de-France",
    note: "Cette entreprise n'existe pas. Profil et chiffres inventés pour la démonstration.",
    figures: [
      ["Chiffre d'affaires annuel", `6,4${nb}M€`],
      ["Collaborateurs", "34"],
      ["Équipe commerciale", "4 personnes"],
      ["Valeur moyenne d'un projet", `18${nn}500${nb}€`],
      ["Demandes par mois", "225"],
    ] as [string, string][],
  },
  player: {
    aria: "Démonstration Revenue OS",
    play: "Lecture",
    pause: "Pause",
    restart: "Recommencer",
    previous: "Étape précédente",
    next: "Étape suivante",
    stages: "Étapes de la démonstration",
    stage: "Étape",
    of: "sur",
    workspace: "Élan Habitat · Revenue OS",
    reduced: "Animations réduites : chaque étape s'affiche en entier. Utilisez les flèches pour avancer.",
  },
  nav: {
    enquiry: "Demande",
    response: "Réponse",
    qualification: "Qualification",
    crm: "CRM",
    routing: "Attribution",
    brief: "Brief",
    appointment: "Rendez-vous",
    aftercall: "Après l'appel",
    proposal: "Proposition",
    reactivation: "Réactivation",
    dashboard: "Direction",
    finale: "Le système",
  } as Record<DemoStageId, string>,

  enquiry: {
    time: "09:42:06",
    kicker: "Nouvelle demande",
    title: "Une demande arrive.",
    caption: "Un matin de semaine, depuis le site. Revenue OS la reçoit à la seconde — quel que soit le canal.",
    channels: ["Site web", "Téléphone", "E-mail", "Messagerie", "Recommandation"],
    source: "Site web · formulaire de devis",
    customerLabel: "Client",
    customer: "Thomas Martin",
    locationLabel: "Localisation",
    location: "Lille",
    messageLabel: "Message",
    message: "« Bonjour, nous souhaitons refaire complètement notre cuisine et ouvrir la pièce sur le séjour. »",
    gloss: "",
    received: "Demande reçue",
  },

  response: {
    time: "09:42:09",
    kicker: "Réponse",
    title: "Réponse lancée.",
    caption: "Trois secondes plus tard, Thomas reçoit une réponse au nom d'Élan Habitat — et Revenue OS recueille ce qu'un conseiller demanderait.",
    channel: "Messagerie Élan Habitat",
    agent: "Élan Habitat",
    customer: "Thomas",
    messages: [
      { from: "os", text: "Bonjour Thomas, merci pour votre demande. Pour préparer un premier échange utile : quelle est la surface de la cuisine, et l'ouverture concerne-t-elle un mur porteur ?" },
      { from: "customer", text: "Environ 14 m². Oui, c'est un mur porteur — maison de 1930." },
      { from: "os", text: "Merci. Avez-vous une enveloppe budgétaire en tête, et une échéance ?" },
      { from: "customer", text: "Entre 20 et 30 000 €. Idéalement dans les deux mois." },
      { from: "os", text: "Êtes-vous propriétaire occupant ? Préférez-vous un appel ou un rendez-vous, et à quel moment ?" },
      { from: "customer", text: "Oui, propriétaires. Un rendez-vous plutôt, en matinée." },
    ],
    collectingLabel: "Informations recueillies",
    collecting: ["Type de projet", "Localisation", "Budget", "Échéance", "Bien", "Disponibilités", "Contact préféré"],
    /* Message après lequel chaque information est acquise (index 1 à 6). */
    collectedAfter: [2, 0, 4, 4, 6, 6, 6],
    note: "Conversation illustrative. Le ton, les questions et les limites sont définis par l'entreprise.",
  },

  qualification: {
    time: "09:43:21",
    kicker: "Qualification",
    title: "Une qualification claire.",
    caption: "Les réponses deviennent une fiche lisible : ce qu'il faut savoir, et à quel point c'est sérieux.",
    fields: [
      ["Projet", "Rénovation complète de cuisine + ouverture structurelle"],
      ["Localisation", "Lille"],
      ["Budget", `20${nn}000 – 30${nn}000${nb}€`],
      ["Échéance", "Sous 60 jours"],
      ["Bien", "Maison, propriétaire occupant"],
    ] as [string, string][],
    statusLabel: "Statut",
    status: "Forte intention commerciale",
    scoreLabel: "Score",
    score: 89,
    factorsLabel: "Ce qui compte",
    factors: [
      ["Budget compatible", true],
      ["Échéance sous 60 jours", true],
      ["Propriétaire décisionnaire", true],
      ["Travaux structurels : étude à prévoir", false],
    ] as [string, boolean][],
  },

  crm: {
    time: "09:43:34",
    kicker: "CRM",
    title: "Le CRM se remplit seul.",
    caption: "Aucune ressaisie : chaque information arrive dans le bon champ, avec sa source.",
    record: "Opportunité · Thomas Martin",
    recordId: "OPP-2481",
    fields: [
      ["Client", "Thomas Martin"],
      ["Projet", "Cuisine ouverte sur séjour, mur porteur"],
      ["Budget", `20${nn}000 – 30${nn}000${nb}€`],
      ["Localisation", "Lille"],
      ["Échéance", "Sous 60 jours"],
      ["Source", "Site web · formulaire de devis"],
      ["Score d'intention", "89 / 100"],
      ["Notes", "Maison de 1930, 14 m². Préfère un rendez-vous en matinée."],
    ] as [string, string][],
    synced: "CRM synchronisé",
  },

  routing: {
    time: "09:43:36",
    kicker: "Attribution",
    title: "Opportunité attribuée.",
    caption: "La bonne personne, du premier coup — selon des règles que l'entreprise a choisies.",
    team: [
      { name: "Sophie", role: "Conseillère projet", detail: "Lille · Rénovation", chosen: true },
      { name: "Julien", role: "Conseiller projet", detail: "Arras · Extensions", chosen: false },
      { name: "Inès", role: "Conseillère projet", detail: "Lens · Rénovation énergétique", chosen: false },
      { name: "Marc", role: "Conseiller projet", detail: "Lille · Agenda complet", chosen: false },
    ],
    reasonsLabel: "Pourquoi Sophie",
    reasons: ["Secteur de Lille", "Spécialiste rénovation", "Capacité disponible", "Opportunité à forte valeur"],
    assigned: "Attribuée à Sophie — Conseillère projet",
  },

  brief: {
    time: "09:43:41",
    kicker: "Brief commercial",
    title: "Sophie sait à qui elle parle.",
    caption: "Avant même le premier échange, un brief prêt à l'emploi — celui qu'un commercial aimerait recevoir.",
    doc: "Brief commercial",
    for: "Pour Sophie · Thomas Martin",
    sections: [
      { label: "Synthèse", body: "Thomas souhaite une refonte complète de sa cuisine avec des travaux structurels. Le budget est compatible avec la fourchette de projets habituelle d'Élan Habitat. Échéance visée : sous 60 jours." },
      { label: "Points clés", list: ["Mur porteur, maison de 1930 : prévoir une étude de structure", "Pièce de 14 m² ouverte sur le séjour", "Propriétaires occupants, décision à deux"] },
      { label: "À préparer", list: ["Deux références de cuisines ouvertes", "Délai indicatif du bureau d'études"] },
      { label: "Questions ouvertes", list: ["Plans de la maison disponibles ?", "Contraintes de copropriété : aucune (maison)"] },
    ],
    nextLabel: "Prochaine action recommandée",
    next: "Consultation de conception",
    footer: "Généré par Revenue OS · relu par la conseillère avant usage",
  },

  appointment: {
    time: "09:45:04",
    kicker: "Rendez-vous",
    title: "Thomas choisit son créneau.",
    caption: "Les disponibilités réelles de Sophie, proposées dans la conversation. Tout le reste suit.",
    days: [
      { day: "Lun.", slots: ["14:00"] },
      { day: "Mar.", slots: ["09:00", "10:30", "16:00"] },
      { day: "Mer.", slots: ["11:00"] },
      { day: "Jeu.", slots: ["09:30", "15:00"] },
      { day: "Ven.", slots: ["10:00"] },
    ],
    chosenDay: 1,
    chosenSlot: 1,
    picked: "Thomas sélectionne mardi, 10:30",
    booked: "Rendez-vous réservé",
    bookedDetail: "Mardi · 10:30 · Consultation de conception avec Sophie",
    effects: ["CRM mis à jour", "Agenda mis à jour", "Conseillère notifiée", "Confirmation envoyée au client", "Rappel programmé"],
    statLabel: "Demande → rendez-vous qualifié",
    stat: "≈ 3 minutes",
    statNote: "Durée illustrative du parcours.",
  },

  aftercall: {
    time: "Mardi · 11:24",
    kicker: "Après l'appel",
    title: "Le compte rendu est prêt.",
    caption: "Consultation terminée. Revenue OS prépare la suite ; ce qui engage l'entreprise reste validé par une personne.",
    done: "Consultation terminée · 52 min",
    items: [
      { label: "Compte rendu", body: "Cuisine ouverte, îlot central, rangements toute hauteur. Couple très attentif au calendrier." },
      { label: "Besoins", body: "Ouverture du mur porteur, reprise électrique, sol continu cuisine-séjour." },
      { label: "Actions", body: "Visite technique jeudi · demande au bureau d'études · envoi de deux références." },
      { label: "Notes CRM", body: "Budget confirmé 25 – 30 k€. Décision commune, sous trois semaines.", approval: "Validé par Sophie" },
      { label: "Éléments pour le devis", body: "Métrés, gamme de façades, poste structure, options d'électroménager.", approval: "À valider par le métreur" },
      { label: "Prochaine étape", body: "Envoyer la proposition sous 5 jours ouvrés." },
    ],
    human: "Validation humaine",
  },

  proposal: {
    time: "J+0 → J+8",
    kicker: "Proposition",
    title: "Le devis ne tombe jamais dans l'oubli.",
    caption: "Revenue OS ne garantit pas la signature. Il fait en sorte qu'aucune proposition ne reste sans prochaine action.",
    doc: "Proposition · Cuisine ouverte",
    customer: "Thomas Martin",
    amount: `24${nn}800${nb}€`,
    status: "Envoyée",
    timeline: [
      { day: "J+0", label: "Proposition envoyée", kind: "done" },
      { day: "J+2", label: "Relance — message approuvé, envoyé", kind: "done" },
      { day: "J+5", label: "Rappel à Sophie : appeler Thomas", kind: "done" },
      { day: "J+8", label: "Opportunité à risque — pas de réponse", kind: "risk" },
    ],
    nextLabel: "Prochaine action",
    next: "Sophie appelle Thomas — aujourd'hui",
    emphasis: "Chaque opportunité a une prochaine action visible.",
  },

  reactivation: {
    time: "Mercredi · 08:30",
    kicker: "Deuxième scénario — Réactivation",
    title: "Votre prochain client vous connaît peut-être déjà.",
    caption: "Revenue OS repère, dans l'historique, les projets reportés qui méritent un nouveau contact.",
    crm: "CRM · demandes historiques",
    count: 3240,
    filters: ["Projet reporté", "Plus de 6 mois", "Salle de bain & cuisine"],
    rows: [
      ["Hugo Lefebvre", "Extension", "il y a 14 mois", "Perdu — concurrent"],
      ["Claire Bernard", "Rénovation salle de bain", "il y a 7 mois", "Projet reporté"],
      ["Sarah Dubois", "Cuisine", "il y a 11 mois", "Sans suite"],
      ["Paul Moreau", "Isolation", "il y a 9 mois", "Projet reporté"],
    ] as [string, string, string, string][],
    highlight: 1,
    previousLabel: "Demande précédente",
    previous: "il y a 7 mois",
    statusLabel: "Statut",
    status: "Projet reporté",
    workflowLabel: "Parcours de réactivation",
    workflow: ["Segment identifié", "Message rédigé", "Approuvé par le responsable commercial", "Envoyé"],
    reply: "« Oui, le projet est de nouveau d'actualité. »",
    replyGloss: "",
    outcomes: ["Opportunité rouverte", "Qualification mise à jour", "Rendez-vous proposé", "Pipeline mis à jour"],
    note: "Les parcours de réactivation se configurent selon les autorisations et exigences applicables à chaque contact.",
  },

  dashboard: {
    time: "Vue direction · 30 jours",
    kicker: "Vue direction",
    title: "La direction voit tout.",
    caption: "Ce qui entre, ce qui avance, ce qui risque de se perdre — sur un seul écran.",
    tag: "Espace Revenue OS illustratif — données fictives",
    metrics: [
      { label: "Nouvelles demandes", value: 225 },
      { label: "Qualifiées", value: 93 },
      { label: "Consultations", value: 38 },
      { label: "Pipeline ouvert", value: 382000, currency: true },
      { label: "Relances à traiter", value: 27 },
      { label: "Opportunités à risque", value: 8, alert: true },
      { label: "Opportunités réactivées", value: 14, gold: true },
    ],
    funnelLabel: "Du premier contact au rendez-vous",
    funnel: [
      ["Demandes", 225],
      ["Qualifiées", 93],
      ["Consultations", 38],
    ] as [string, number][],
    riskLabel: "À traiter aujourd'hui",
    risks: [
      ["Thomas Martin · Cuisine", "Proposition J+8 sans réponse"],
      ["Famille Roux · Extension", "Relance non envoyée"],
      ["L. Garnier · Salle de bain", "Rendez-vous à confirmer"],
    ] as [string, string][],
  },

  finale: {
    kicker: "Le système",
    title: "Un seul système.",
    caption: "Chaque canal, chaque outil, chaque personne : reliés par Revenue OS.",
    nodes: ["Site web", "Téléphone", "E-mail", "CRM", "Agenda", "Ventes", "Automatisation", "Direction"],
    core: "Revenue OS",
    lines: ["Une demande.", "Un système.", "Zéro chaos."],
    brand: "AMYN Revenue OS™",
    tagline: "De la demande au chiffre d'affaires. Une seule infrastructure.",
    primary: "Demander votre Revenue Audit",
    secondary: "Parler à AMYN",
    sample: "Voir un exemple de Revenue Audit",
  },

  after: {
    label: "Aller plus loin",
    title: [{ text: "La démonstration montre le système." }, { text: "L'audit montre", accent: "le vôtre." }] as HeadingLine[],
    lead: "Le Revenue Audit part de votre parcours réel — vos canaux, vos outils, vos délais — et indique où Revenue OS serait utile, et où il ne le serait pas.",
    sampleTitle: "Exemple de Revenue Audit",
    sampleBody: "Le rendu complet d'un audit, préparé pour Élan Habitat. Entreprise fictive.",
    sampleCta: "Ouvrir l'exemple",
  },
};

export type DemoCopy = typeof fr;

const en: DemoCopy = {
  meta: {
    title: "Revenue OS in action — interactive demonstration",
    description:
      "Follow one enquiry through Revenue OS, from the first second to the proposal: response, qualification, CRM, routing, sales brief, appointment, follow-up, reactivation and the management view. Fictional company, illustrative data.",
  },
  fictional: "Fictional demonstration — illustrative data",
  fictionalShort: "Fictional",
  hero: {
    label: "Interactive demonstration",
    title: [{ text: "Revenue OS," }, { accent: "in action." }],
    lead: "A renovation company receives an enquiry one morning at 09:42. This is what Revenue OS does — from the first second to the proposal, and beyond.",
    start: "Start the demonstration",
    duration: "About two minutes · pause and navigate at any time",
  },
  company: {
    name: "Élan Habitat",
    kind: "Premium residential renovation",
    location: "Lille & Hauts-de-France",
    note: "This company does not exist. Profile and figures invented for the demonstration.",
    figures: [
      ["Annual revenue", "€6.4M"],
      ["Employees", "34"],
      ["Sales team", "4 people"],
      ["Average project value", "€18,500"],
      ["Enquiries per month", "225"],
    ],
  },
  player: {
    aria: "Revenue OS demonstration",
    play: "Play",
    pause: "Pause",
    restart: "Restart",
    previous: "Previous stage",
    next: "Next stage",
    stages: "Demonstration stages",
    stage: "Stage",
    of: "of",
    workspace: "Élan Habitat · Revenue OS",
    reduced: "Reduced motion: each stage is shown in full. Use the arrows to move on.",
  },
  nav: {
    enquiry: "Enquiry",
    response: "Response",
    qualification: "Qualification",
    crm: "CRM",
    routing: "Routing",
    brief: "Brief",
    appointment: "Appointment",
    aftercall: "After the call",
    proposal: "Proposal",
    reactivation: "Reactivation",
    dashboard: "Management",
    finale: "The system",
  },

  enquiry: {
    time: "09:42:06",
    kicker: "New enquiry",
    title: "An enquiry arrives.",
    caption: "A weekday morning, from the website. Revenue OS receives it within the second — whatever the channel.",
    channels: ["Website", "Phone", "Email", "Messaging", "Referral"],
    source: "Website · quote form",
    customerLabel: "Customer",
    customer: "Thomas Martin",
    locationLabel: "Location",
    location: "Lille",
    messageLabel: "Message",
    message: "“Bonjour, nous souhaitons refaire complètement notre cuisine et ouvrir la pièce sur le séjour.”",
    gloss: "“Hello, we'd like to completely redo our kitchen and open the room onto the living area.”",
    received: "Enquiry received",
  },

  response: {
    time: "09:42:09",
    kicker: "Response",
    title: "Response initiated.",
    caption: "Three seconds later, Thomas receives a reply in Élan Habitat's name — and Revenue OS gathers what an advisor would ask.",
    channel: "Élan Habitat messaging",
    agent: "Élan Habitat",
    customer: "Thomas",
    messages: [
      { from: "os", text: "Hello Thomas, thank you for your enquiry. To prepare a useful first conversation: how large is the kitchen, and does the opening involve a load-bearing wall?" },
      { from: "customer", text: "About 14 m². Yes, it's load-bearing — a 1930s house." },
      { from: "os", text: "Thank you. Do you have a budget in mind, and a timeframe?" },
      { from: "customer", text: "Between €20k and €30k. Ideally within two months." },
      { from: "os", text: "Do you own and live in the property? Would you prefer a call or an appointment, and when?" },
      { from: "customer", text: "Yes, we own it. An appointment, ideally in the morning." },
    ],
    collectingLabel: "Information collected",
    collecting: ["Project type", "Location", "Budget", "Timeline", "Property", "Availability", "Preferred contact"],
    collectedAfter: [2, 0, 4, 4, 6, 6, 6],
    note: "Illustrative conversation. Tone, questions and limits are defined by the business.",
  },

  qualification: {
    time: "09:43:21",
    kicker: "Qualification",
    title: "A clear qualification.",
    caption: "The answers become a readable record: what matters, and how serious it is.",
    fields: [
      ["Project", "Complete kitchen renovation + structural opening"],
      ["Location", "Lille"],
      ["Budget", "€20,000–€30,000"],
      ["Timeline", "Within 60 days"],
      ["Property", "Owner-occupied house"],
    ],
    statusLabel: "Status",
    status: "High commercial intent",
    scoreLabel: "Lead score",
    score: 89,
    factorsLabel: "What counts",
    factors: [
      ["Budget compatible", true],
      ["Timeline under 60 days", true],
      ["Owner is the decision-maker", true],
      ["Structural work: survey needed", false],
    ],
  },

  crm: {
    time: "09:43:34",
    kicker: "CRM",
    title: "The CRM fills itself.",
    caption: "No re-typing: every piece of information lands in the right field, with its source.",
    record: "Opportunity · Thomas Martin",
    recordId: "OPP-2481",
    fields: [
      ["Customer", "Thomas Martin"],
      ["Project", "Kitchen opened onto living room, load-bearing wall"],
      ["Budget", "€20,000–€30,000"],
      ["Location", "Lille"],
      ["Timeline", "Within 60 days"],
      ["Lead source", "Website · quote form"],
      ["Intent score", "89 / 100"],
      ["Notes", "1930s house, 14 m². Prefers a morning appointment."],
    ],
    synced: "CRM synchronized",
  },

  routing: {
    time: "09:43:36",
    kicker: "Routing",
    title: "Opportunity routed.",
    caption: "The right person, first time — following rules the business has chosen.",
    team: [
      { name: "Sophie", role: "Project Advisor", detail: "Lille · Renovation", chosen: true },
      { name: "Julien", role: "Project Advisor", detail: "Arras · Extensions", chosen: false },
      { name: "Inès", role: "Project Advisor", detail: "Lens · Energy retrofit", chosen: false },
      { name: "Marc", role: "Project Advisor", detail: "Lille · Calendar full", chosen: false },
    ],
    reasonsLabel: "Why Sophie",
    reasons: ["Lille territory", "Renovation specialization", "Available capacity", "High-value lead"],
    assigned: "Assigned to Sophie — Project Advisor",
  },

  brief: {
    time: "09:43:41",
    kicker: "Sales brief",
    title: "Sophie knows who she's talking to.",
    caption: "Before the first conversation, a ready-to-use brief — the one a salesperson actually wants to receive.",
    doc: "Sales brief",
    for: "For Sophie · Thomas Martin",
    sections: [
      { label: "Summary", body: "Thomas wants a complete kitchen redesign with structural work. Budget is compatible with Élan Habitat's usual project range. Target timeline: within 60 days." },
      { label: "Key points", list: ["Load-bearing wall in a 1930s house: plan a structural survey", "14 m² room opening onto the living area", "Owner-occupiers, a joint decision"] },
      { label: "To prepare", list: ["Two open-plan kitchen references", "Indicative lead time from the structural engineer"] },
      { label: "Open questions", list: ["Are house plans available?", "Co-ownership constraints: none (house)"] },
    ],
    nextLabel: "Recommended next action",
    next: "Design consultation",
    footer: "Generated by Revenue OS · reviewed by the advisor before use",
  },

  appointment: {
    time: "09:45:04",
    kicker: "Appointment",
    title: "Thomas picks his slot.",
    caption: "Sophie's real availability, offered in the conversation. Everything else follows.",
    days: [
      { day: "Mon", slots: ["14:00"] },
      { day: "Tue", slots: ["09:00", "10:30", "16:00"] },
      { day: "Wed", slots: ["11:00"] },
      { day: "Thu", slots: ["09:30", "15:00"] },
      { day: "Fri", slots: ["10:00"] },
    ],
    chosenDay: 1,
    chosenSlot: 1,
    picked: "Thomas selects Tuesday, 10:30",
    booked: "Appointment booked",
    bookedDetail: "Tuesday · 10:30 · Design consultation with Sophie",
    effects: ["CRM updated", "Calendar updated", "Salesperson notified", "Customer confirmation sent", "Reminder scheduled"],
    statLabel: "Enquiry → qualified appointment",
    stat: "≈ 3 minutes",
    statNote: "Illustrative workflow timing.",
  },

  aftercall: {
    time: "Tuesday · 11:24",
    kicker: "After the call",
    title: "The call notes are ready.",
    caption: "Consultation completed. Revenue OS prepares what comes next; anything that commits the business is still approved by a person.",
    done: "Consultation completed · 52 min",
    items: [
      { label: "Call summary", body: "Open-plan kitchen, central island, full-height storage. The couple cares a lot about timing." },
      { label: "Requirements", body: "Load-bearing wall opening, electrical rework, continuous floor from kitchen to living room." },
      { label: "Action items", body: "Technical visit Thursday · request to structural engineer · send two references." },
      { label: "CRM notes", body: "Budget confirmed €25–30k. Joint decision, within three weeks.", approval: "Approved by Sophie" },
      { label: "Quote inputs", body: "Measurements, cabinet range, structural line item, appliance options.", approval: "Awaiting estimator approval" },
      { label: "Next step", body: "Send the proposal within 5 working days." },
    ],
    human: "Human approval",
  },

  proposal: {
    time: "Day 0 → Day 8",
    kicker: "Proposal",
    title: "The proposal is never forgotten.",
    caption: "Revenue OS doesn't guarantee the signature. It makes sure no proposal is left without a next action.",
    doc: "Proposal · Open-plan kitchen",
    customer: "Thomas Martin",
    amount: "€24,800",
    status: "Sent",
    timeline: [
      { day: "Day 0", label: "Proposal sent", kind: "done" },
      { day: "Day 2", label: "Follow-up — approved message, sent", kind: "done" },
      { day: "Day 5", label: "Reminder to Sophie: call Thomas", kind: "done" },
      { day: "Day 8", label: "At-risk opportunity — no reply", kind: "risk" },
    ],
    nextLabel: "Next action",
    next: "Sophie calls Thomas — today",
    emphasis: "Every opportunity has a visible next action.",
  },

  reactivation: {
    time: "Wednesday · 08:30",
    kicker: "Second scenario — Reactivation",
    title: "Your next customer may already know you.",
    caption: "Revenue OS finds, in your history, the postponed projects worth a new conversation.",
    crm: "CRM · historical enquiries",
    count: 3240,
    filters: ["Project postponed", "Over 6 months", "Bathroom & kitchen"],
    rows: [
      ["Hugo Lefebvre", "Extension", "14 months ago", "Lost — competitor"],
      ["Claire Bernard", "Bathroom renovation", "7 months ago", "Project postponed"],
      ["Sarah Dubois", "Kitchen", "11 months ago", "No follow-up"],
      ["Paul Moreau", "Insulation", "9 months ago", "Project postponed"],
    ],
    highlight: 1,
    previousLabel: "Previous enquiry",
    previous: "7 months ago",
    statusLabel: "Status",
    status: "Project postponed",
    workflowLabel: "Reactivation workflow",
    workflow: ["Segment identified", "Message drafted", "Approved by the sales manager", "Sent"],
    reply: "“Oui, le projet est de nouveau d'actualité.”",
    replyGloss: "“Yes, the project is back on.”",
    outcomes: ["Opportunity reopened", "Qualification updated", "Appointment offered", "Pipeline updated"],
    note: "Reactivation workflows must be configured according to the permissions and requirements that apply to each contact.",
  },

  dashboard: {
    time: "Management view · 30 days",
    kicker: "Management view",
    title: "Management sees everything.",
    caption: "What comes in, what moves forward, what risks being lost — on a single screen.",
    tag: "Illustrative Revenue OS workspace — fictional data",
    metrics: [
      { label: "New enquiries", value: 225 },
      { label: "Qualified", value: 93 },
      { label: "Consultations", value: 38 },
      { label: "Open pipeline", value: 382000, currency: true },
      { label: "Follow-ups requiring action", value: 27 },
      { label: "At-risk opportunities", value: 8, alert: true },
      { label: "Reactivated opportunities", value: 14, gold: true },
    ],
    funnelLabel: "From first contact to consultation",
    funnel: [
      ["Enquiries", 225],
      ["Qualified", 93],
      ["Consultations", 38],
    ],
    riskLabel: "To handle today",
    risks: [
      ["Thomas Martin · Kitchen", "Proposal at day 8, no reply"],
      ["Roux family · Extension", "Follow-up not sent"],
      ["L. Garnier · Bathroom", "Appointment to confirm"],
    ],
  },

  finale: {
    kicker: "The system",
    title: "One system.",
    caption: "Every channel, every tool, every person: connected through Revenue OS.",
    nodes: ["Website", "Phone", "Email", "CRM", "Calendar", "Sales", "Automation", "Management"],
    core: "Revenue OS",
    lines: ["One lead.", "One system.", "Zero chaos."],
    brand: "AMYN Revenue OS™",
    tagline: "From enquiry to revenue. One infrastructure.",
    primary: "Request your Revenue Audit",
    secondary: "Talk to AMYN",
    sample: "See a sample Revenue Audit",
  },

  after: {
    label: "Going further",
    title: [{ text: "The demonstration shows the system." }, { text: "The audit shows", accent: "yours." }],
    lead: "The Revenue Audit starts from your real journey — your channels, your tools, your response times — and shows where Revenue OS would help, and where it wouldn't.",
    sampleTitle: "Sample Revenue Audit",
    sampleBody: "The full deliverable of an audit, prepared for Élan Habitat. Fictional company.",
    sampleCta: "Open the sample",
  },
};

const copy: Record<Locale, DemoCopy> = { fr, en };
export const getDemo = (locale: Locale): DemoCopy => copy[locale];
