import type { RevenueAudit } from "../../lib/audit/types.ts";

/**
 * FICTIONAL SAMPLE — Élan Habitat does not exist.
 * English version of the sample audit (see elan-habitat.fr.ts).
 */
export const elanHabitatEn: RevenueAudit = {
  slug: "elan-habitat-sample",
  locale: "en",
  status: "ready",
  fictional: true,
  company: {
    name: "Élan Habitat",
    domain: "elan-habitat.example",
    industry: "Premium residential renovation",
    country: "France",
  },
  date: "2026-10-05",
  preparedBy: "Amine Kammour — AMYN",
  summary: {
    context:
      "Élan Habitat receives a high volume of enquiries for a four-person sales team. The challenge is not attracting more enquiries, but handling better the ones that already arrive.",
    primaryRecommendation: "Structure response and qualification from the moment of enquiry, then give every proposal a visible next action.",
  },

  sources: [
    { id: "S1", kind: "website", label: "“Request a quote” page", url: "https://elan-habitat.example/devis", date: "2026-09-29" },
    { id: "S2", kind: "website", label: "Confirmation page after form submission", url: "https://elan-habitat.example/devis/merci", date: "2026-09-29" },
    { id: "S3", kind: "public_listing", label: "Online business listing", date: "2026-09-29" },
    { id: "S4", kind: "call", label: "Preliminary conversation with the sales director", date: "2026-09-30" },
    { id: "S5", kind: "questionnaire", label: "Revenue Audit questionnaire completed by the company", date: "2026-10-01" },
  ],

  providedMetrics: [
    { id: "M1", label: "Inbound enquiries per month", value: "≈ 225", source: "S5", note: "Company estimate" },
    { id: "M2", label: "Average project value", value: "€18,500", source: "S5" },
    { id: "M3", label: "Sales team", value: "4 advisors", source: "S4" },
    { id: "M4", label: "Historic enquiries", value: "≈ 3,240 since 2019", source: "S4" },
    { id: "M5", label: "Enquiry sources", value: "Website 55% · phone 25% · referrals and trade shows 20%", source: "S5" },
  ],

  scores: [
    { id: "leadCapture", points: 11, basis: ["O6", "O3"], rationale: "Form reachable from every page, a well-kept business listing, several entry channels. Inbound calls are not logged consistently." },
    { id: "response", points: 7, basis: ["O2"], rationale: "Stated call-back time of 48 working hours; no personalised acknowledgement, no out-of-hours response." },
    { id: "qualification", points: 6, basis: ["O1", "H1"], rationale: "The form collects no qualification information; qualification would happen on the first call (hypothesis to validate)." },
    { id: "followUp", points: 8, basis: ["O4", "H2"], rationale: "Proposal follow-up depends on each advisor, with no shared rule or deadline." },
    { id: "crmHandoff", points: null, basis: [], rationale: "CRM access not yet shared: not enough information to score this dimension." },
    { id: "reactivation", points: 2, basis: ["O5"], rationale: "A large history, never used in a structured way." },
    { id: "visibility", points: 4, basis: ["O7"], rationale: "Tracking consolidated by hand, once a month." },
  ],

  journey: [
    { id: "discovery", status: "verified", note: "Website and business listing observed." },
    { id: "enquiry", status: "verified", note: "Quote form observed; calls not observed." },
    { id: "response", status: "opportunity", note: "Stated time: 48 working hours." },
    { id: "qualification", status: "opportunity", note: "No structured qualification at enquiry." },
    { id: "crm", status: "needs_validation", note: "CRM access to be obtained." },
    { id: "followUp", status: "opportunity", note: "Follow-up without a shared rule (provided)." },
    { id: "meeting", status: "needs_validation", note: "Home consultation (provided)." },
    { id: "proposal", status: "needs_validation", note: "Proposal timing and follow-up to measure." },
    { id: "customer", status: "needs_validation", note: "Handover to the build team outside observed scope." },
  ],

  observations: [
    {
      id: "O1",
      title: "Quote intake",
      provenance: "observed",
      category: "qualification",
      stage: "enquiry",
      statement:
        "The website's primary quote form currently asks for name, email, telephone and a free-text project description. No field captures the type of work, budget, timeline or property.",
      sources: ["S1"],
      confidence: "high",
      implication: "The sales team may need to perform additional manual qualification after enquiry.",
      recommendation: "Consider introducing structured qualification while keeping the initial experience friction-light.",
    },
    {
      id: "O2",
      title: "Stated call-back time",
      provenance: "observed",
      category: "response",
      stage: "response",
      statement: "The page shown after submitting the form reads: “We will get back to you within 48 working hours.”",
      sources: ["S2"],
      confidence: "high",
      implication: "An enquiry sent on a Friday evening may wait until Tuesday; in the meantime, the prospect may contact other companies.",
      recommendation: "Acknowledge immediately and start qualification at enquiry, including outside business hours.",
    },
    {
      id: "O3",
      title: "Enquiry volume and sources",
      provenance: "provided",
      category: "leadCapture",
      stage: "enquiry",
      statement: "The company reports around 225 enquiries per month: 55% via the website, 25% by phone, 20% from referrals and trade shows.",
      sources: ["S5"],
      confidence: "medium",
      implication: "For four advisors, this volume would mean more than 50 enquiries per person per month, before any qualification.",
      recommendation: "Sort and prioritise enquiries as they arrive, so advisors spend their time on high-intent projects.",
    },
    {
      id: "O4",
      title: "Proposal follow-up",
      provenance: "provided",
      category: "followUp",
      stage: "followUp",
      statement: "The sales director reports that proposal follow-up is left to each advisor's judgement, with no shared rule or deadline.",
      sources: ["S4"],
      confidence: "high",
      implication: "A proposal can be left without an identified next action, without anyone noticing.",
      recommendation: "Define a shared follow-up sequence, with reminders and an alert for at-risk opportunities.",
    },
    {
      id: "O5",
      title: "Historic enquiries",
      provenance: "provided",
      category: "reactivation",
      statement: "The company keeps around 3,240 enquiries since 2019, split between a spreadsheet and CRM exports.",
      sources: ["S4"],
      confidence: "medium",
      implication: "Some of these enquiries may concern postponed projects that could become relevant again.",
      recommendation: "Segment the history and prepare approved reactivation workflows, configured according to the permissions that apply to each contact.",
    },
    {
      id: "O6",
      title: "Online presence",
      provenance: "observed",
      category: "leadCapture",
      stage: "discovery",
      statement: "The business listing is complete (hours, service area, project photos) and reviews receive regular replies.",
      sources: ["S3"],
      confidence: "high",
      implication: "Discovery is a strength: the difficulty would lie after the enquiry, not before.",
      recommendation: "Keep this foundation; no priority work on acquisition.",
    },
    {
      id: "O7",
      title: "Management tracking",
      provenance: "provided",
      category: "visibility",
      statement: "Sales tracking is consolidated once a month in a spreadsheet, from information sent by each advisor.",
      sources: ["S4"],
      confidence: "high",
      implication: "Management would see gaps up to a month late.",
      recommendation: "A dashboard fed continuously by the CRM, focused on next actions and at-risk opportunities.",
    },
  ],

  hypotheses: [
    {
      id: "H1",
      title: "Qualification on the first call",
      category: "qualification",
      statement: "Qualification may mainly happen during the first call, using advisor time on early-stage enquiries.",
      validation: "Review twenty recent enquiries with the team, and the time spent before the first appointment.",
    },
    {
      id: "H2",
      title: "Proposals without a next action",
      category: "followUp",
      statement: "Some proposals unanswered after seven days may have no planned next action.",
      validation: "Export from the CRM the proposals of the last 90 days and their latest activity.",
    },
    {
      id: "H3",
      title: "Information lost between phone and CRM",
      category: "crmHandoff",
      statement: "Some information gathered by phone may not be entered in the CRM.",
      validation: "Compare, with the team, a sample of calls and the matching CRM records.",
    },
  ],

  opportunities: [
    { id: "P1", title: "Structured qualification at enquiry", summary: "Capture project type, budget, timeline and property before the first call.", impact: 3, confidence: 3, complexity: 1, relevance: 3, basis: ["O1", "O3"] },
    { id: "P2", title: "Instant response, including out of hours", summary: "A personalised acknowledgement and the first questions within seconds.", impact: 3, confidence: 3, complexity: 1, relevance: 3, basis: ["O2"] },
    { id: "P3", title: "Proposal follow-up discipline", summary: "A shared sequence, reminders, an alert at day 8.", impact: 3, confidence: 2, complexity: 2, relevance: 3, basis: ["O4", "H2"] },
    { id: "P4", title: "Continuous management view", summary: "Pipeline, next actions and risks, updated daily.", impact: 2, confidence: 3, complexity: 2, relevance: 2, basis: ["O7"] },
    { id: "P5", title: "Reactivating the history", summary: "Postponed projects, re-engaged through an approved workflow.", impact: 2, confidence: 2, complexity: 2, relevance: 2, basis: ["O5"] },
    { id: "P6", title: "Inbound call traceability", summary: "Every call logged as an enquiry, with its context.", impact: 2, confidence: 1, complexity: 3, relevance: 2, basis: ["O3", "H3"] },
  ],

  recommendations: [
    {
      module: "aiReception",
      priority: "critical",
      what: "Instant acknowledgement and first exchanges in Élan Habitat's name, on the website and by email, within the tone and limits set by the team.",
      why: "The stated 48-working-hour delay leaves enquiries unanswered, especially at weekends.",
      impact: "Every enquiry gets a reply within seconds; advisors pick up conversations already under way.",
      basis: ["O2"],
    },
    {
      module: "qualification",
      priority: "critical",
      what: "Conversational qualification questions and a structured record: project, budget, timeline, property, availability.",
      why: "The form collects no qualification information.",
      impact: "Advisors know, before calling, which enquiries to handle first.",
      basis: ["O1", "O3", "H1"],
    },
    {
      module: "followUp",
      priority: "critical",
      what: "Shared follow-up sequence, approved messages, advisor reminders and a day-8 alert.",
      why: "Proposal follow-up currently depends on each advisor.",
      impact: "No proposal left without a visible next action.",
      basis: ["O4", "H2"],
    },
    {
      module: "crmAutomation",
      priority: "high",
      what: "Records created and updated automatically from conversations, with the source of each piece of information.",
      why: "Information gathered by phone may not be entered (to validate).",
      impact: "Complete records without re-typing; a reliable history for follow-up and reactivation.",
      basis: ["H3", "O1"],
    },
    {
      module: "calendar",
      priority: "high",
      what: "Advisors' real availability offered in the conversation, with automatic confirmation and reminder.",
      why: "With more than 50 enquiries per advisor per month, scheduling takes time.",
      impact: "Fewer back-and-forths between enquiry and consultation.",
      basis: ["O3"],
    },
    {
      module: "proposalWorkflow",
      priority: "high",
      what: "Tracking of every proposal: sent, opened, followed up, status, at-risk opportunities.",
      why: "The proposal is where opportunities are lost most quietly.",
      impact: "A clear view of open proposals, by advisor.",
      basis: ["O4"],
    },
    {
      module: "routing",
      priority: "medium",
      what: "Assignment by territory, specialisation and each advisor's workload.",
      why: "High volume for a team of four.",
      impact: "A faster, more balanced distribution.",
      basis: ["O3"],
    },
    {
      module: "managementDashboard",
      priority: "medium",
      what: "Management dashboard: enquiries, qualification, appointments, pipeline, next actions, risks.",
      why: "Tracking is currently consolidated by hand, once a month.",
      impact: "Management sees gaps day by day.",
      basis: ["O7"],
    },
    {
      module: "reactivation",
      priority: "medium",
      what: "Segmentation of the history and approved reactivation workflows, configured according to applicable permissions.",
      why: "Around 3,240 enquiries kept, never used in a structured way.",
      impact: "Postponed projects identified and re-engaged at the right time.",
      basis: ["O5"],
    },
    {
      module: "salesCopilot",
      priority: "future",
      what: "Pre-meeting briefs and post-consultation summaries.",
      why: "Useful once qualification and the CRM are reliable.",
      impact: "Better-prepared consultations.",
      basis: ["O3"],
    },
  ],

  roi: {
    assumptions: [
      { key: "monthlyLeads", value: 225, origin: "provided", note: "Questionnaire (S5)" },
      { key: "dealValue", value: 18500, origin: "provided", note: "Questionnaire (S5)" },
      { key: "qualificationRate", value: 41, origin: "hypothesis", note: "AMYN hypothesis, to validate from the CRM" },
      { key: "closeRate", value: 22, origin: "hypothesis", note: "AMYN hypothesis, to validate from the CRM" },
      { key: "historicLeads", value: 3240, origin: "provided", note: "Conversation (S4)" },
      { key: "grossMargin", value: null, origin: "provided", note: "Not provided" },
    ],
    scenarios: {
      conservative: { qualificationLift: 1, closeLift: 0.5, reactivationRate: 0.5 },
      central: { qualificationLift: 2, closeLift: 1, reactivationRate: 1 },
      upside: { qualificationLift: 4, closeLift: 2, reactivationRate: 2 },
    },
  },
};
