#!/usr/bin/env node
/**
 * Bundles the migrations into one file that can be pasted into the Supabase SQL
 * editor, for setting up a project without installing anything.
 *
 *   npm run db:bundle
 *
 * The output is committed so it can be opened and copied straight from GitHub, and a
 * test asserts it still matches the migrations — so the two can never drift apart.
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const from = resolve(root, 'supabase/migrations');
const to = resolve(root, 'supabase/dist');

/**
 * Objects that one migration creates and a later one removes.
 *
 * `ai_usage` and `increment_ai_usage` are created by 20260101000000_init and dropped by
 * 20260101000300_subscriptions, which replaced the daily counter with period metering.
 * Replaying that is right for an existing project — that is what `supabase db push`
 * does — but this bundle exists to build a *new* database, where creating a table,
 * enabling RLS on it, giving it a policy and a function, and then dropping the lot is
 * pure churn that contributes nothing to the final schema.
 *
 * It is also churn with a cost: it is the one part of the bundle whose correctness
 * depends on statements executing in exactly the emitted order, which is precisely
 * what a browser SQL editor does not guarantee. Emitting the destination schema
 * instead of the journey removes the ordering dependency altogether.
 *
 * Every cut is asserted, and the invariant at the end is what actually guarantees
 * correctness: no reference to the superseded objects may survive.
 */
function dropSupersededObjects(sql) {
  const cuts = [
    [/-- Daily counter used to enforce[^\n]*\ncreate table public\.ai_usage \([\s\S]*?\n\);\n\n/, ''],
    [/'ai_memory','ai_usage',/, "'ai_memory',"],
    [/-- ai_usage is a server-side counter[^\n]*\ncreate policy "own usage read"[^\n]*\n/, ''],
    [/-- Server-owned usage counter[^\n]*\ncreate or replace function public\.increment_ai_usage[\s\S]*?end \$\$;\n\nrevoke all on function public\.increment_ai_usage[^\n]*\n\n/, ''],
    [/-- The old daily counter is replaced[^\n]*\ndrop function if exists public\.increment_ai_usage[^\n]*\ndrop table if exists public\.ai_usage;\n/, ''],
  ];

  for (const [pattern, replacement] of cuts) {
    if (!pattern.test(sql)) {
      throw new Error(
        `build-sql: the migrations changed and this cut no longer matches: ${pattern}. ` +
        'Update dropSupersededObjects rather than letting the bundle drift.',
      );
    }
    sql = sql.replace(pattern, replacement);
  }

  if (/ai_usage/.test(sql)) {
    throw new Error('build-sql: a reference to ai_usage survived the fresh-install cuts.');
  }
  return sql;
}

export function buildSql() {
  const files = readdirSync(from).filter((f) => f.endsWith('.sql')).sort();

  const header = `-- ============================================================================
-- LifeOS — complete database setup
--
-- Generated by scripts/build-sql.mjs from supabase/migrations. Do not edit by hand:
-- edit the migrations and run \`npm run db:bundle\`.
--
-- To set up a Supabase project without installing anything:
--   1. Supabase dashboard → SQL Editor → New query
--   2. Paste this whole file
--   3. Run
--   4. Then do the same with supabase/tests/verify.sql to check it worked
--
-- This file is one transaction. Either the whole schema is created or nothing is —
-- there is no state in between. That matters because a paste into a browser editor
-- can be cut short, and a half-applied schema is far harder to diagnose than an
-- empty one: the errors it produces afterwards point at whatever statement happened
-- to run first, not at the truncation that actually caused them. If the run does not
-- reach COMMIT, the database is left exactly as it was and you can simply paste again.
--
-- Running it twice is not supported: it creates types and tables, so start from a
-- project where these do not exist yet.
--
-- ${files.length} migrations, in order:
${files.map((f) => `--   ${f}`).join('\n')}
-- ============================================================================

begin;

`;

  // A truncated paste stops before this, so the transaction never commits.
  const footer = `

do $lifeos_done$
begin
  raise notice 'LifeOS schema created: ${files.length} migrations applied in one transaction.';
end $lifeos_done$;

commit;

-- ============================================================================
-- END OF FILE. If you did not see the notice above, the paste was incomplete and
-- nothing was applied — paste the whole file again.
-- ============================================================================
`;

  const body = files
    .map((file) => {
      const banner = `-- ${'─'.repeat(74)}\n-- ${file}\n-- ${'─'.repeat(74)}\n`;
      return banner + readFileSync(resolve(from, file), 'utf8').trimEnd() + '\n';
    })
    .join('\n');

  return { files, sql: header + dropSupersededObjects(body) + footer };
}

// `file://${process.argv[1]}` is not a valid file URL on Windows (backslashes, no
// drive-letter encoding) and silently never matches, which used to make this whole
// block a no-op there: `npm run db:bundle` produced nothing, and the "is the bundle
// stale" check always reported success without checking anything. pathToFileURL fixes
// both platforms the same way.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { files, sql } = buildSql();
  const target = resolve(to, 'all-migrations.sql');

  // `--check` verifies the committed bundle is current without rewriting it, so CI
  // and the test suite can catch drift.
  if (process.argv.includes('--check')) {
    const committed = existsSync(target) ? readFileSync(target, 'utf8') : '';
    if (committed !== sql) {
      console.error('supabase/dist/all-migrations.sql is stale. Run: npm run db:bundle');
      process.exit(1);
    }
    console.log('supabase/dist/all-migrations.sql is up to date.');
    process.exit(0);
  }

  mkdirSync(to, { recursive: true });
  writeFileSync(target, sql);
  console.log(
    `Bundled ${files.length} migrations into supabase/dist/all-migrations.sql (${sql.split('\n').length} lines).`,
  );
}
