#!/usr/bin/env node
/**
 * Bundles the migrations into one file that can be pasted into the Supabase SQL
 * editor, for setting up a project without installing anything.
 *
 *   npm run db:bundle
 *
 * The output is committed so it can be opened and copied straight from GitHub, and a
 * test asserts it still matches the migrations — so the two can never drift apart.
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const from = resolve(root, 'supabase/migrations');
const to = resolve(root, 'supabase/dist');

export function buildSql() {
  const files = readdirSync(from).filter((f) => f.endsWith('.sql')).sort();

  const header = `-- ============================================================================
-- LifeOS — complete database setup
--
-- Generated by scripts/build-sql.mjs from supabase/migrations. Do not edit by hand:
-- edit the migrations and run \`npm run db:bundle\`.
--
-- To set up a Supabase project without installing anything:
--   1. Supabase dashboard → SQL Editor → New query
--   2. Paste this whole file
--   3. Run
--   4. Then do the same with supabase/tests/verify.sql to check it worked
--
-- This file is one transaction. Either the whole schema is created or nothing is —
-- there is no state in between. That matters because a paste into a browser editor
-- can be cut short, and a half-applied schema is far harder to diagnose than an
-- empty one: the errors it produces afterwards point at whatever statement happened
-- to run first, not at the truncation that actually caused them. If the run does not
-- reach COMMIT, the database is left exactly as it was and you can simply paste again.
--
-- Running it twice is not supported: it creates types and tables, so start from a
-- project where these do not exist yet.
--
-- ${files.length} migrations, in order:
${files.map((f) => `--   ${f}`).join('\n')}
-- ============================================================================

begin;

`;

  // A truncated paste stops before this, so the transaction never commits.
  const footer = `

do $lifeos_done$
begin
  raise notice 'LifeOS schema created: ${files.length} migrations applied in one transaction.';
end $lifeos_done$;

commit;

-- ============================================================================
-- END OF FILE. If you did not see the notice above, the paste was incomplete and
-- nothing was applied — paste the whole file again.
-- ============================================================================
`;

  const body = files
    .map((file) => {
      const banner = `-- ${'─'.repeat(74)}\n-- ${file}\n-- ${'─'.repeat(74)}\n`;
      return banner + readFileSync(resolve(from, file), 'utf8').trimEnd() + '\n';
    })
    .join('\n');

  return { files, sql: header + body + footer };
}

// `file://${process.argv[1]}` is not a valid file URL on Windows (backslashes, no
// drive-letter encoding) and silently never matches, which used to make this whole
// block a no-op there: `npm run db:bundle` produced nothing, and the "is the bundle
// stale" check always reported success without checking anything. pathToFileURL fixes
// both platforms the same way.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { files, sql } = buildSql();
  const target = resolve(to, 'all-migrations.sql');

  // `--check` verifies the committed bundle is current without rewriting it, so CI
  // and the test suite can catch drift.
  if (process.argv.includes('--check')) {
    const committed = existsSync(target) ? readFileSync(target, 'utf8') : '';
    if (committed !== sql) {
      console.error('supabase/dist/all-migrations.sql is stale. Run: npm run db:bundle');
      process.exit(1);
    }
    console.log('supabase/dist/all-migrations.sql is up to date.');
    process.exit(0);
  }

  mkdirSync(to, { recursive: true });
  writeFileSync(target, sql);
  console.log(
    `Bundled ${files.length} migrations into supabase/dist/all-migrations.sql (${sql.split('\n').length} lines).`,
  );
}
