import type { SessionDTO } from '@devisia/shared';

export type MobileLocale = 'fr' | 'en';

/**
 * Compact native dictionary for the shared mobile shell. Product content
 * generated by the API remains locale-aware; these labels keep the native
 * chrome, auth, billing and support surfaces in the selected language too.
 */
const DICTIONARY = {
  fr: {
    home: 'Accueil', clients: 'Clients', activity: 'Activité', space: 'Mon espace', create: 'Créer',
    directory: 'Répertoire', yourClients: 'Vos clients', account: 'Mon compte', discover: 'Découvrir DEVISERA',
    subscription: 'Abonnement', pricing: 'Catalogue de prix', business: 'Mon entreprise', analytics: 'Activité',
    manageProfile: 'Gérer mon profil', language: 'Langue de l’application', french: 'Français', english: 'English',
    rate: 'Noter l’application', contact: 'Nous contacter', payments: 'Paiements et factures', manageApple: 'Gérer mon abonnement Apple',
    support: 'Contacter DEVISERA', retry: 'Réessayer', save: 'Enregistrer', signOut: 'Se déconnecter',
    login: 'Se connecter', createAccount: 'Créer un compte', email: 'Adresse email', password: 'Mot de passe',
    verify: 'Vérifiez votre adresse', verifySent: 'Un code vient d’être envoyé', confirm: 'Confirmer mon adresse', resend: 'Renvoyer un code',
  },
  en: {
    home: 'Home', clients: 'Clients', activity: 'Activity', space: 'My space', create: 'Create',
    directory: 'Directory', yourClients: 'Your clients', account: 'My account', discover: 'Discover DEVISERA',
    subscription: 'Subscription', pricing: 'Price catalogue', business: 'My business', analytics: 'Activity',
    manageProfile: 'Manage my profile', language: 'App language', french: 'Français', english: 'English',
    rate: 'Rate the app', contact: 'Contact us', payments: 'Payments & invoices', manageApple: 'Manage Apple subscription',
    support: 'Contact DEVISERA', retry: 'Try again', save: 'Save', signOut: 'Sign out',
    login: 'Sign in', createAccount: 'Create an account', email: 'Email address', password: 'Password',
    verify: 'Verify your email', verifySent: 'A verification code was sent', confirm: 'Confirm my email', resend: 'Send a new code',
  },
} as const;

export type MobileCopyKey = keyof typeof DICTIONARY.fr;

export function mobileLocale(session: Pick<SessionDTO, 'user'> | null | undefined): MobileLocale {
  return session?.user.locale === 'en' ? 'en' : 'fr';
}

export function deviceLocale(): MobileLocale {
  try { return Intl.DateTimeFormat().resolvedOptions().locale.toLowerCase().startsWith('en') ? 'en' : 'fr'; }
  catch { return 'fr'; }
}

export function copy(locale: MobileLocale, key: MobileCopyKey): string {
  return DICTIONARY[locale][key];
}
